import 'help_models.dart';

/// Web `en.ts` / `tr.ts` + FAQ locale dosyalarıyla hizalı (otomatik üretildi — `tool/generate_help_bundles.py`).
const HelpCenterBundle kHelpBundleTr = HelpCenterBundle(
  howItWorks: HowItWorksCopy(
    heroTitle: "Tiempos nasıl çalışır",
    heroSubtitle: "Beceri takası ve topluluk oluşturmak için basit ve adil bir yol",
    getStartedFree: "Ücretsiz başla",
    stepsTitle: "Dört basit adım",
    stepsSubtitle: "Dakikalar içinde öğrenmeye başlayın",
    steps: <HowItWorksStep>[
    HowItWorksStep(number: "01", title: "Profilini oluştur", description: "Kayıt ol, becerilerini ve öğrenmek istediklerini anlat. Başlamak sadece 2 dakika sürer."),
    HowItWorksStep(number: "02", title: "Göz at ve bağlan", description: "Topluluğumuzun sunduğu yüzlerce beceriyi keşfet. İlgi alanlarına ve takvimine göre eşleş."),
    HowItWorksStep(number: "03", title: "Beceri takası yap", description: "Bildiğini öğret, öğrenmek istediğini öğren. Her öğrettiğin saat zaman kredisi kazandırır."),
    HowItWorksStep(number: "04", title: "Birlikte büyü", description: "Profilini geliştir ve yaşam boyu öğrenenler topluluğunun parçası ol."),
    ],
    creditsTitle: "Zaman kredilerini anlamak",
    creditsIntro: "Zaman kredileri Tiempos'un para birimidir. Sistem son derece basit:",
    teachHour: "1 saat öğretim = 1 zaman kredisi",
    teachHourSub: "Bilgini paylaşarak kredi kazan",
    learnHour: "1 zaman kredisi = 1 saat öğrenme",
    learnHourSub: "Kredileri herhangi bir şey öğrenmek için harca",
    bonusTitle: "Yeni üye bonusu",
    bonusCredits: "1 ücretsiz zaman kredisi",
    bonusDesc: "Yeni üyeler 1 zaman kredisiyle (1 saat öğrenme) başlar. Hemen başla — önce öğretmen olmana gerek yok.",
    claimBonus: "Bonusunu al",
    whyTitle: "Neden Tiempos?",
    benefits: <String>[
    "Para gerekmez — zamanı zamana takas et",
    "Topluluğundaki tutkulu uzmanlardan öğren",
    "Esnek program — kendi hızında öğren",
    "Anlamlı bağlar kur",
    "Güvenli ve doğrulanmış üyeler",
    "Öğrenme ilerlemeni takip et",
    ],
    faqTitle: "Sıkça sorulan sorular",
    miniFaqs: <({String q, String a})>[
    (q: "Zaman kredileri nasıl işler?", a: "Her öğrettiğin saat için bir zaman kredisi kazanırsın. Bu kredileri başkalarından öğrenmek için harcarsın. Adil ve eşit bir takas sistemidir."),
    (q: "Öğretecek becerim yoksa?", a: "Herkesin paylaşacak bir şeyi vardır! Yemek, bahçecilik, konuştuğun bir dil veya mesleki uzmanlık — Tiempos'ta tüm beceriler değerlidir."),
    (q: "Hem öğrenip hem öğretebilir miyim?", a: "Kesinlikle! Üyelerimizin çoğu hem öğretmen hem öğrenci. Öğretirken aynı anda yeni şeyler öğrenebilirsin."),
    (q: "Tiempos ücretsiz mi?", a: "Evet! Hesap oluşturmak ve beceri takası tamamen ücretsiz. Öğrenmeyi herkes için erişilebilir kılmayı hedefliyoruz."),
    (q: "İlk zaman kredilerimi nasıl alırım?", a: "Yeni üyeler hemen öğrenmeye başlamak için 1 saatlik ücretsiz zaman kredisi alır. Daha fazla kredi için hemen öğretmeye de başlayabilirsin."),
    ],
    ctaTitle: "Öğrenmeye hazır mısın?",
    ctaSubtitle: "Topluluğumuzdaki binlerce öğrenci ve öğretmene katıl",
    ctaButton: "Ücretsiz hesap oluştur",
  ),
  about: AboutCopy(
    heroTitle: "Tiempos hakkında",
    heroSubtitle: "Zamanın para birimi, becerilerin özgürce paylaşıldığı bir topluluk kuruyoruz",
    missionTitle: "Misyonumuz",
    missionP1: "Tiempos güçlü ama basit bir fikirden doğdu: herkesin öğretebileceği bir şey ve öğrenmek istediği bir şey var. Bilginin maddi engellerin arkasında kilitli olmaması gerektiğine inanıyoruz.",
    missionP2: "Platformumuzda beceriler zaman para birimiyle takas edilir. Bir saat öğretmenlik, başka birinden bir saat öğrenmeye eşittir. Adil, sade ve gerçek bağlar kurar.",
    statMembers: "Doğrulanmış üyeler",
    statSkills: "Yayınlanan beceriler",
    statHours: "Takas edilen saat (tamamlanan)",
    statSatisfaction: "Memnuniyet (değerlendirmeler)",
    valuesTitle: "Değerlerimiz",
    values: <AboutValue>[
    AboutValue(title: "Önce topluluk", body: "Herkesin katkıda bulunduğu ve eşit şekilde fayda gördüğü güçlü, destekleyici topluluklar kurarız."),
    AboutValue(title: "Adalet", body: "Zaman tabanlı takas, beceri ne olursa olsun herkesin katkısının eşit değer görmesini sağlar."),
    AboutValue(title: "Kaliteli öğrenme", body: "Değerlendirme sistemimiz ve topluluk kurallarımızla kaliteli takasları destekleriz."),
    AboutValue(title: "Erişilebilirlik", body: "Bilgi, önünde maddi engeller olmadan herkese açık olmalıdır."),
    AboutValue(title: "Gelişim", body: "Tüm üyeler için sürekli öğrenmeyi ve kişisel gelişimi teşvik ederiz."),
    AboutValue(title: "Zamana saygı", body: "Herkesin zamanına eşit değer verir, saygılı ve sorunsuz takaslar hedefleriz."),
    ],
    storyTitle: "Hikayemiz",
    storyParagraphs: <String>[
    "Tiempos, 2024'te eğitimciler ve geliştiricilerin ortak bir vizyonla bir araya gelmesiyle başladı: öğrenmenin maddi durumdan bağımsız olarak herkese erişilebilir olduğu bir dünya.",
    "Geleneksel eğitim platformlarının, öğrenmek isteyen ama ücreti karşılayamayan insanları dışarıda bıraktığını gördük. Öte yandan birçok yetenekli insan bilgisini paylaşmak istiyor ama nereden başlayacağını bilmiyor.",
    "Zamanı para birimi olarak kullanarak gerçekten eşitlikçi bir platform oluşturduk. İster ileri düzey programlama ister başlangıç seviyesi yemek pişirme öğretin—saatiniz aynı değerde. Bu ilke, hayatın her alanından öğrenci ve eğitmenlerden oluşan çeşitli ve aktif bir topluluk kurmamıza yardımcı oldu.",
    "Bugün Tiempos büyümeye devam ediyor; dünya çapında binlerce insanı bir araya getiriyor, anlamlı bağlar kuruyor ve bilgi ile topluluk gibi hayattaki en iyi şeylerin etiket gerektirmediğini gösteriyor.",
    ],
    ctaTitle: "Topluluğumuza katılmaya hazır mısınız?",
    ctaSubtitle: "Becerilerinizi paylaşın, başkalarından öğrenin. Ücretsiz, adil ve keyifli!",
    ctaButton: "Başlayın",
  ),
  faq: FaqPageCopy(
    heroTitle: "Sıkça sorulan sorular",
    heroSubtitle: "Tiempos hakkında merak edilenlere hızlı yanıtlar",
    searchPlaceholder: "Sorularda ara…",
    emptyText: "Aramanızla eşleşen soru bulunamadı.",
    ctaTitle: "Hâlâ sorunuz mu var?",
    ctaText: "Aradığınız yanıtı bulamadınız mı? Destek ekibimiz size yardımcı olmak için burada.",
    ctaButton: "İletişime geçin",
    categories: <FaqCategory>[
    FaqCategory(id: "all", label: "Tüm sorular"),
    FaqCategory(id: "general", label: "Genel"),
    FaqCategory(id: "getting-started", label: "Başlangıç"),
    FaqCategory(id: "sessions", label: "Oturumlar"),
    FaqCategory(id: "credits", label: "Zaman kredileri"),
    FaqCategory(id: "safety", label: "Güvenlik"),
    FaqCategory(id: "technical", label: "Teknik"),
    ],
    items: <FaqItem>[
    FaqItem(id: 1, category: "general", q: "Tiempos nedir?", a: "Tiempos, kullanıcıların becerileri zaman para birimiyle takas ettiği bir platformdur. Para ödemek yerine öğretme saatlerinizi öğrenme saatleriyle değiştirirsiniz."),
    FaqItem(id: 2, category: "general", q: "Zaman kredisi sistemi nasıl işler?", a: "Her yeni kullanıcı 1 saatlik ücretsiz zaman kredisi ile başlar. Birine 1 saat öğrettiğinizde 1 kredi kazanırsınız; birinden 1 saat öğrendiğinizde 1 kredi harcarsınız. Tüm beceriler süre açısından eşit değerlendirilir."),
    FaqItem(id: 3, category: "general", q: "Tiempos ücretsiz mi?", a: "Evet! Tiempos tamamen ücretsizdir. Bilginin herkese açık olması gerektiğine inanıyoruz. Ödeme yalnızca başkalarına öğreterek zamanınızla yapılır."),
    FaqItem(id: 4, category: "getting-started", q: "Nasıl başlarım?", a: "Ücretsiz hesap oluşturun, profilinizi tamamlayın, öğretebileceğiniz becerileri ekleyin ve öğrenmek istediğiniz becerilere göz atın. İlk oturumunuzu ayırmak için 1 saatlik ücretsiz zaman kredisi ile başlarsınız."),
    FaqItem(id: 5, category: "getting-started", q: "Hangi becerileri öğretebilir veya öğrenebilirim?", a: "Neredeyse her şey! Programlama ve tasarımdan yemek ve müziğe kadar. Bir oturumda öğretilebilecek bir beceri ise Tiempos'ta paylaşabilirsiniz."),
    FaqItem(id: 6, category: "getting-started", q: "Yeni beceri nasıl eklerim?", a: "Kontrol panelinize gidin ve “Beceri ekle”ye tıklayın. Sunduğunuz içeriği, müsaitliğinizi doldurun ve yayınlayın. Beceriniz diğer kullanıcılara hemen görünür."),
    FaqItem(id: 7, category: "sessions", q: "Oturumlar nasıl işler?", a: "Bir oturum ayırdığınızda eğitmenin iletişim bilgilerini alırsınız. İki taraf da kabul ederse çevrim içi (görüntülü görüşme) veya yüz yüze buluşabilirsiniz. Oturumdan sonra her iki taraf tamamlamayı onaylar ve değerlendirme bırakır."),
    FaqItem(id: 8, category: "sessions", q: "Planlanmış bir oturuma katılamazsam ne olur?", a: "Oturumdan en az 24 saat önce cezasız iptal edebilirsiniz; zaman kredileriniz iade edilir. Geç iptallerde kredi kesintisi olabilir."),
    FaqItem(id: 9, category: "sessions", q: "Oturumlar ne kadar sürer?", a: "Çoğu oturum 1 saattir; daha derinlemesine öğrenmek için birden fazla saat ayırabilirsiniz. Süre rezervasyon sırasında kararlaştırılır."),
    FaqItem(id: 10, category: "credits", q: "Zaman kredim biterse ne yaparım?", a: "Başkalarına öğreterek daha fazla kredi kazanabilirsiniz! Öğrettiğiniz her saat için 1 kredi kazanıp yeni şeyler öğrenmek için kullanabilirsiniz."),
    FaqItem(id: 11, category: "credits", q: "Zaman kredisi satın alabilir miyim?", a: "Hayır; zaman kredisi satın alınamaz. Bu, adilliği ve eşit takası korur. Kredileri yalnızca beceri katkınızla kazanırsınız."),
    FaqItem(id: 12, category: "credits", q: "Zaman kredilerinin süresi doluyor mu?", a: "Hayır! Kredilerinizin süresi dolmaz. İstediğiniz zaman biriktirip yeni bir şey öğrenmeye hazır olduğunuzda kullanırsınız."),
    FaqItem(id: 13, category: "safety", q: "Tiempos güvenli mi?", a: "Evet! Kullanıcıları doğrular, değerlendirme sistemi ve topluluk kurallarımız vardır. İlk oturumlar için çevrim içi buluşmayı; yüz yüze için ise kalabalık yerleri öneririz."),
    FaqItem(id: 14, category: "safety", q: "Başka bir kullanıcıyla sorun yaşarsam ne yapmalıyım?", a: "Sorunları destek sistemimiz üzerinden bildirebilirsiniz. Tüm bildirimleri ciddiye alır ve inceleriz. Ağır ihlaller hesap askıya alınmasına yol açabilir."),
    FaqItem(id: 15, category: "technical", q: "Tiempos'u mobilde kullanabilir miyim?", a: "Evet! Tiempos duyarlıdır ve mobilde iyi çalışır. iOS ve Android için özel uygulamalar üzerinde de çalışıyoruz."),
    FaqItem(id: 16, category: "technical", q: "Şifremi unuttum, ne yapmalıyım?", a: "Giriş sayfasında “Şifremi unuttum”a tıklayın. E-posta adresinize sıfırlama bağlantısı göndeririz. Görünmezse spam klasörünü kontrol edin."),
    ],
  ),
  community: StaticTwoField(title: "Topluluk", body: "Topluluk, sizsiniz. Her yayınlanan beceri, tamamlanan oturum ve değerlendirme ağı güçlendirir.\n\nSaygılı olun, saatinde bulunun, net iletişim kurun. Sorunları Destek üzerinden bildirin. Birlikte takası adil ve güvenli tutarız."),
  contact: ContactPageCopy(
    heroTitle: "İletişime geçin",
    heroSubtitle: "Sorularınız mı var? Mesajınızı bekliyoruz; en kısa sürede yanıtlıyoruz.",
    infoTitle: "İletişim bilgileri",
    infoIntro: "Bize e-posta ile ulaşabilirsiniz; yardımcı olmaktan memnuniyet duyarız.",
    emailTitle: "E-posta",
    emailAddress: "tiempos.site@gmail.com",
    responseTitle: "Yanıt süresi",
    responseText: "İş günlerinde genelde 24 saat içinde e-posta ile döneriz.",
    formTitle: "Bize yazın",
    labelName: "Ad Soyad",
    labelEmail: "E-posta",
    labelSubject: "Konu",
    labelMessage: "Mesaj",
    placeholderName: "Ad Soyad",
    placeholderEmail: "ornek@email.com",
    placeholderMessage: "Nasıl yardımcı olabileceğimizi yazın…",
    subjectPlaceholder: "Konu seçin",
    subjectGeneral: "Genel bilgi",
    subjectSupport: "Teknik destek",
    subjectBilling: "Fatura / ödeme",
    subjectPartnership: "İş birliği",
    subjectFeedback: "Geri bildirim",
    subjectOther: "Diğer",
    sendButton: "Mesajı gönder",
    sending: "Gönderiliyor…",
    successTitle: "Mesajınız iletildi!",
    successText: "İletişime geçtiğiniz için teşekkürler. En kısa sürede size döneceğiz.",
    errorSend: "Mesaj gönderilemedi. Lütfen tekrar deneyin veya doğrudan e-posta yazın.",
    errorSendAuth: "Sunucu isteği reddetti (hesap girişi ile ilgili değil). Frontend’i kendiniz barındırıyorsanız VITE_API_BASE_URL yalnızca API ana makinesi olmalı (sonunda /api olmamalı) veya barındırıcıda /api trafiğinin backend’e yönlendirildiğinden emin olun. Yine de aşağıdaki e-posta adresine yazabilirsiniz.",
    errorSendNotFound: "İletişim adresi bulunamadı (404). Statik siteyi VITE_API_BASE_URL Spring API kökünü gösterecek şekilde yeniden derleyin veya /api trafiğini backend’e yönlendiren bir adres kullanın. Yine de aşağıdaki e-postaya yazabilirsiniz.",
    errorUnavailable: "E-posta gönderilemedi (genel). Render API servisindeki SMTP ayarlarını veya aşağıdaki adresi kullanın.",
    errorSmtpNotReady: "Sunucuda giden posta (SMTP) yapılandırması eksik. Render’da API servisine ekleyin: SPRING_MAIL_HOST (ör. smtp-relay.brevo.com), SPRING_MAIL_PORT=587, SPRING_MAIL_USERNAME ve SPRING_MAIL_PASSWORD (Brevo Transactional → SMTP’deki giriş; API key değil), STARTTLS/auth property’leri ve Brevo’da doğrulanmış bir APP_MAIL_FROM. Alternatif: yalnızca BREVO_API_KEY (Brevo → API keys, HTTPS) ekleyerek iletişim formunu SMTP olmadan çalıştırabilirsiniz. Yine de tiempos.site@gmail.com adresine yazabilirsiniz.",
    errorSmtpSendFailed: "SMTP bağlantısı kuruldu ama gönderim reddedildi veya hata verdi. Brevo’da APP_MAIL_FROM ile aynı göndericiyi doğrulayın; şifre olarak SMTP anahtarını (xsmtpsib-...) kullanın; kullanıcı adını Brevo SMTP ekranındakiyle birebir aynı yapın. Ayrıntı için Render API loglarına bakın. Yine de tiempos.site@gmail.com adresine yazabilirsiniz.",
    faqSectionTitle: "Hızlı cevaplar mı arıyorsunuz?",
    faqSectionText: "Yaygın soruların yanıtları için SSS sayfamıza göz atın.",
    faqButton: "SSS’ye git",
  ),
  support: StaticTwoField(title: "Destek ve yardım", body: "Yardıma mı ihtiyacınız var? Önce Nasıl çalışır, İptal ve no-show politikası ve Eğitmen rehberi sayfalarına bakın. Takıldıysanız support@tiempos.local adresine hesap e-postanızı ve kısa açıklamayı yazın.\n\nHer anlaşmazlığa arabuluculuk yapamayız; ancak kötüye kullanım ve tekrarlayan no-show modellerini ciddiye alır, topluluğu korumak için hesap kısıtlayabiliriz."),
  terms: LegalDocCopy(title: "Kullanım şartları", heroSubtitle: "Tiempos'u adil ve güvenli kullanma kuralları: profil, davranış ve zaman kredileri.", body: "Tiempos'ta hesap oluşturup hizmeti kullanarak, platformu iyi niyetle kullanmayı kabul edersiniz. Profil bilgilerinizi doğru tutar, diğer üyelere saygılı davranır ve yürürlükteki yasalara uyarsınız.\n\nZaman kredileri yasal para değildir, nakde çevrilemez ve nakit değeri yoktur; yalnızca uygulama içinde beceri takası ve oturum akışını düzenlemek içindir.\n\nÖzellikleri değiştirebilir, kötüye kullanım, taciz veya tekrarlayan ihlallerde hesapları askıya alabilir veya kısıtlayabilir, gerekli durumlarda uygulama içi bildirimlerle haber verebiliriz.\n\nŞartları güncellersek makul ölçüde bildirim yapılır; güncellemeden sonra kullanımı sürdürmek güncel şartları kabul sayılır.\n\nBu metin geliştirme amaçlı sade bir özettir. Canlıya çıkmadan önce tam hukuki metin uzman avukatla hazırlanmalıdır."),
  privacy: LegalDocCopy(title: "Gizlilik politikası", heroSubtitle: "Hesap ve profil verilerinin kullanımı, görünürlük ve güvenlik hakkında özet bilgi.", body: "Tiempos; hesap ve oturum bilgilerinizi, eklediğiniz profil alanlarını, rezervasyon ve mesajlaşma ile bildirim süreçlerinde oluşan verileri ve hizmeti güvenli çalıştırmak için gerekli teknik kayıtları işleyebilir.\n\nGörünürlük: Yayınladığınız profil bilgileri, her ekranda ve ayarlarınızda belirtildiği şekilde diğer oturum açmış üyelere gösterilebilir. Kişisel verilerinizi üçüncü taraflara “satmak” iş modelimiz değildir.\n\nÇerezler ve güvenlik: Oturum açma, tercihler ve güvenlik için gerekli olduğu ölçüde çerez veya benzeri teknolojiler kullanılabilir. Güçlü ve benzersiz bir şifre kullanın; hesap bilgilerinizi paylaşmayın.\n\nSaklama ve silme: Hesap silme talebinde bulunabilirsiniz. Yasal zorunluluk, ciddi güvenlik veya dolandırıcılık önleme için bazı kayıtların tutulması gerekebilir.\n\nBu özet, geliştirme aşamasında şeffaflık içindir. Canlı ortam için ülkeye özgü tam gizlilik politikası ve veri işleme düzenlemeleri yayımlanmalıdır."),
  policyCancellation: LegalDocCopy(title: "İptal, geç iptal ve no-show", heroSubtitle: "Oturumu ne zaman iptal edebileceğiniz, geç iptal ve gelmeme durumunda beklentiler ve kredi mantığı.", body: "Zaman kredileri genelde eğitmen oturumu ürün içinde “tamamlandı” olarak işaretlendiğinde kesinleşir. Yalnızca rezervasyon veya bekleme durumunda bakiyenizin nasıl etkilendiğini uygulama içi yardımdan doğrulayın.\n\nÜyeler arasında ortak beklenti olarak şunları kullanabilirsiniz:\n\n— Planlanan başlangıçtan 2 saatten fazla önce: iptal tipik olarak kredi hareketi olmadan yapılabilir (çoğu senaryoda kesin borç henüz oluşmamıştır; uygulamayı kontrol edin).\n\n— Başlangıçtan 1–2 saat önce: geç iptal sayılır; karşı tarafı derhal bilgilendirin. Tekrarlayan örüntüler güven ve topluluk güvenilirliğini etkileyebilir.\n\n— 1 saatten az kala veya hiç gelinmemesi (no-show): oturum düşebilir; eğitmen durumu Destek üzerinden kayda geçirebilir. Tekrarlayan no-show hesap incelemesine yol açabilir.\n\nİş parçacığındaki isteğe bağlı “katılım” bilgisi iki tarafa yardımcı olur; kredi aktarımını belirleyen adım yine eğitmenin tamamlama işlemidir.\n\nBu metin topluluk yönergesidir, hukuki danışmanlık yerine geçmez. Eşik sürelerini kurulumunuza göre güncelleyebilirsiniz."),
  instructorGuide: StaticTwoField(title: "Eğitmen: onay ve oturum akışı", body: "1) Öğrenci talep + zaman önerir. Siz kabul, red veya red + yeni zaman teklif edebilirsiniz (red sonrası).\n\n2) Kabulden sonra sohbet tam açılır. Takvimde çakışan onaylı oturum engellenir. Zoom/Meet veya sınıf linkini oturum kartında paylaşın.\n\n3) Gerçek ders bittiğinde “Oturumu tamamlandı işaretle” ile kredi aktarılır. Sorun varsa, başlangıçtan önce iptal (yukarıdaki politika).\n\n4) İsteğe bağlı: öğrenci “katıldım” onayı verebilir; güvence amaçlı—tamamlandı adımının yerine geçmez."),
);
