import 'help_models.dart';

/// Web `en.ts` / `tr.ts` + FAQ locale dosyalarıyla hizalı (otomatik üretildi — `tool/generate_help_bundles.py`).
const HelpCenterBundle kHelpBundleEn = HelpCenterBundle(
  howItWorks: HowItWorksCopy(
    heroTitle: "How Tiempos Works",
    heroSubtitle: "A simple, fair way to exchange skills and build your community",
    getStartedFree: "Get Started Free",
    stepsTitle: "Four Simple Steps",
    stepsSubtitle: "Start your learning journey in minutes",
    steps: <HowItWorksStep>[
    HowItWorksStep(number: "01", title: "Create Your Profile", description: "Sign up and tell us about your skills and what you'd like to learn. It takes just 2 minutes to get started."),
    HowItWorksStep(number: "02", title: "Browse & Connect", description: "Explore hundreds of skills offered by our community. Find the perfect match based on your interests and schedule."),
    HowItWorksStep(number: "03", title: "Exchange Skills", description: "Teach what you know and learn what you want. Every hour you teach earns you time credits to spend on learning."),
    HowItWorksStep(number: "04", title: "Grow Together", description: "Build your profile and become part of a thriving community of lifelong learners."),
    ],
    creditsTitle: "Understanding Time Credits",
    creditsIntro: "Time credits are the currency of Tiempos. The system is beautifully simple:",
    teachHour: "1 Hour Teaching = 1 Time Credit",
    teachHourSub: "Earn credits by sharing your knowledge",
    learnHour: "1 Time Credit = 1 Hour Learning",
    learnHourSub: "Spend credits to learn anything",
    bonusTitle: "New Member Bonus",
    bonusCredits: "Get 1 Free Time Credit",
    bonusDesc: "New members start with 1 time credit (1 hour of learning). Begin right away — no teaching required first.",
    claimBonus: "Claim Your Bonus",
    whyTitle: "Why Choose Tiempos?",
    benefits: <String>[
    "No money needed - trade time for time",
    "Learn from passionate experts in your community",
    "Flexible scheduling - learn at your own pace",
    "Build meaningful connections",
    "Safe and verified community members",
    "Track your learning progress",
    ],
    faqTitle: "Frequently Asked Questions",
    miniFaqs: <({String q, String a})>[
    (q: "How do time credits work?", a: "For every hour you teach, you earn one time credit. You can then spend these credits to learn from others. It's a fair, equal exchange system."),
    (q: "What if I don't have any skills to teach?", a: "Everyone has something valuable to share! Whether it's cooking, gardening, a language you speak, or professional expertise - all skills are welcome on Tiempos."),
    (q: "Can I learn and teach at the same time?", a: "Absolutely! Most of our members are both teachers and students. You can offer your skills while simultaneously learning new ones."),
    (q: "Is Tiempos free to use?", a: "Yes! Creating an account and exchanging skills is completely free. We believe in making learning accessible to everyone."),
    (q: "How do I get my first time credits?", a: "New members receive 1 free hour of time credit to begin learning right away. You can also start teaching to earn more credits immediately."),
    ],
    ctaTitle: "Ready to Start Learning?",
    ctaSubtitle: "Join thousands of learners and teachers in our community",
    ctaButton: "Create Free Account",
  ),
  about: AboutCopy(
    heroTitle: "About Tiempos",
    heroSubtitle: "Building a community where time is the currency and skills are shared freely",
    missionTitle: "Our Mission",
    missionP1: "Tiempos was born from a simple yet powerful idea: everyone has something valuable to teach, and everyone has something they want to learn. We believe that knowledge shouldn't be locked behind financial barriers.",
    missionP2: "Our platform enables people to exchange skills using time as currency. One hour of your time teaching equals one hour of learning from someone else. It's fair, it's simple, and it builds genuine connections.",
    statMembers: "Verified members",
    statSkills: "Skills listed",
    statHours: "Hours exchanged (completed)",
    statSatisfaction: "Satisfaction (from reviews)",
    valuesTitle: "Our Values",
    values: <AboutValue>[
    AboutValue(title: "Community First", body: "We believe in building strong, supportive communities where everyone contributes and benefits equally."),
    AboutValue(title: "Fairness", body: "Time-based exchange ensures everyone's contribution is valued equally, regardless of the skill."),
    AboutValue(title: "Quality Learning", body: "We ensure high-quality exchanges through our rating system and community guidelines."),
    AboutValue(title: "Accessibility", body: "Knowledge should be accessible to everyone, without financial barriers standing in the way."),
    AboutValue(title: "Growth", body: "We encourage continuous learning and personal development for all community members."),
    AboutValue(title: "Time Respect", body: "We value everyone's time equally and ensure smooth, respectful exchanges."),
    ],
    storyTitle: "Our Story",
    storyParagraphs: <String>[
    "Tiempos started in 2024 when a group of educators and developers came together with a shared vision: to create a world where learning is accessible to everyone, regardless of their financial situation.",
    "We noticed that traditional educational platforms often exclude talented individuals who want to learn but can't afford the fees. Meanwhile, many skilled people want to share their knowledge but don't know where to start.",
    "By using time as currency, we've created a truly equitable platform. Whether you're teaching advanced programming or beginner cooking, your hour is worth the same. This fundamental principle has helped us build a diverse, engaged community of learners and teachers from all walks of life.",
    "Today, Tiempos continues to grow, connecting thousands of people around the world, fostering meaningful connections, and proving that the best things in life – like knowledge and community – don't need a price tag.",
    ],
    ctaTitle: "Ready to Join Our Community?",
    ctaSubtitle: "Start sharing your skills and learning from others today. It's free, fair, and fun!",
    ctaButton: "Get Started",
  ),
  faq: FaqPageCopy(
    heroTitle: "Frequently Asked Questions",
    heroSubtitle: "Find answers to common questions about Tiempos",
    searchPlaceholder: "Search questions…",
    emptyText: "No questions found matching your search.",
    ctaTitle: "Still have questions?",
    ctaText: "Can't find the answer you're looking for? Our support team is here to help.",
    ctaButton: "Contact us",
    categories: <FaqCategory>[
    FaqCategory(id: "all", label: "All Questions"),
    FaqCategory(id: "general", label: "General"),
    FaqCategory(id: "getting-started", label: "Getting Started"),
    FaqCategory(id: "sessions", label: "Sessions"),
    FaqCategory(id: "credits", label: "Time Credits"),
    FaqCategory(id: "safety", label: "Safety"),
    FaqCategory(id: "technical", label: "Technical"),
    ],
    items: <FaqItem>[
    FaqItem(id: 1, category: "general", q: "What is Tiempos?", a: "Tiempos is a skill exchange platform where users trade skills using time as currency. Instead of paying money, you exchange hours of teaching for hours of learning."),
    FaqItem(id: 2, category: "general", q: "How does the time credit system work?", a: "Every new user starts with 1 free hour of time credit. When you teach someone for 1 hour, you earn 1 credit. When you learn from someone for 1 hour, you spend 1 credit. All skills are valued equally in terms of time."),
    FaqItem(id: 3, category: "general", q: "Is Tiempos free to use?", a: "Yes! Tiempos is completely free. We believe knowledge should be accessible to everyone. You only “pay” with your time by teaching others."),
    FaqItem(id: 4, category: "getting-started", q: "How do I get started?", a: "Simply sign up for a free account, complete your profile, add the skills you can teach, and browse available skills you'd like to learn. You'll start with 1 free hour of time credit to book your first session."),
    FaqItem(id: 5, category: "getting-started", q: "What skills can I teach or learn?", a: "Almost anything! From programming and design to cooking and music. If it's a skill that can be taught in a session, you can share it on Tiempos."),
    FaqItem(id: 6, category: "getting-started", q: "How do I add a new skill?", a: "Go to your Dashboard and click “Add Skill”. Fill in the details about what you're offering, set your availability, and publish it. Your skill will be visible to other users immediately."),
    FaqItem(id: 7, category: "sessions", q: "How do sessions work?", a: "Once you book a session, you'll receive the teacher's contact information. You can meet online (via video call) or in-person if both parties agree. After the session, both users confirm completion and leave ratings."),
    FaqItem(id: 8, category: "sessions", q: "What happens if I can't attend a scheduled session?", a: "You can cancel up to 24 hours before the session without penalty. Your time credits will be refunded. Late cancellations may result in credit deduction."),
    FaqItem(id: 9, category: "sessions", q: "How long are sessions?", a: "Most sessions are 1 hour, but you can book multiple hours for more in-depth learning. The duration is agreed upon when booking."),
    FaqItem(id: 10, category: "credits", q: "What if I run out of time credits?", a: "You can earn more credits by teaching others! Each hour you teach earns you 1 credit that you can use to learn something new."),
    FaqItem(id: 11, category: "credits", q: "Can I buy time credits?", a: "No, time credits cannot be purchased. This ensures fairness and maintains the community spirit of equal exchange. You earn credits by contributing your skills."),
    FaqItem(id: 12, category: "credits", q: "Do time credits expire?", a: "No! Your time credits never expire. You can save them up and use them whenever you're ready to learn something new."),
    FaqItem(id: 13, category: "safety", q: "Is Tiempos safe?", a: "Yes! We verify all users, maintain a rating system, and have community guidelines. We recommend meeting online for your first few sessions and always meeting in public places for in-person sessions."),
    FaqItem(id: 14, category: "safety", q: "What if I have a problem with another user?", a: "You can report any issues through our support system. We take all reports seriously and will investigate accordingly. Serious violations may result in account suspension."),
    FaqItem(id: 15, category: "technical", q: "Can I use Tiempos on mobile?", a: "Yes! Tiempos is fully responsive and works great on mobile devices. We're also working on dedicated mobile apps for iOS and Android."),
    FaqItem(id: 16, category: "technical", q: "I forgot my password. What should I do?", a: "Click “Forgot Password” on the login page. We'll send you a reset link to your email address. Make sure to check your spam folder if you don't see it."),
    ],
  ),
  community: StaticTwoField(title: "Community", body: "You are the community. Every published skill, every completed session, and every review strengthens the network.\n\nBe respectful, show up on time, and communicate clearly. Report problems through Support so we can help. Together we keep the exchange fair and welcoming."),
  contact: ContactPageCopy(
    heroTitle: "Get in Touch",
    heroSubtitle: "Have questions? We'd love to hear from you. Send us a message and we'll respond as soon as possible.",
    infoTitle: "Contact Information",
    infoIntro: "Reach us by email — we're here to help.",
    emailTitle: "Email",
    emailAddress: "tiempos.site@gmail.com",
    responseTitle: "Response Time",
    responseText: "We typically respond within 24 hours on business days.",
    formTitle: "Send us a Message",
    labelName: "Full Name",
    labelEmail: "Email Address",
    labelSubject: "Subject",
    labelMessage: "Message",
    placeholderName: "John Doe",
    placeholderEmail: "john@example.com",
    placeholderMessage: "Tell us how we can help you…",
    subjectPlaceholder: "Select a subject",
    subjectGeneral: "General inquiry",
    subjectSupport: "Technical support",
    subjectBilling: "Billing question",
    subjectPartnership: "Partnership",
    subjectFeedback: "Feedback",
    subjectOther: "Other",
    sendButton: "Send Message",
    sending: "Sending…",
    successTitle: "Message sent!",
    successText: "Thank you for contacting us. We'll get back to you soon.",
    errorSend: "Your message could not be sent. Please try again or email us directly.",
    errorSendAuth: "The server blocked this request (not an account sign-in issue). If you deploy the frontend yourself, set VITE_API_BASE_URL to the API host only (no /api suffix) or configure your host to forward /api to the backend. You can still email us below.",
    errorSendNotFound: "The contact endpoint was not found (404). Rebuild the static site with VITE_API_BASE_URL pointing to your Spring API, or open the site from a host that forwards /api to the backend. You can still email us below.",
    errorUnavailable: "Email could not be sent (generic). Check SMTP on the Render API service or write to tiempos.site@gmail.com.",
    errorSmtpNotReady: "Outbound email (SMTP) is not set up on the server. On the Render API service, set SPRING_MAIL_HOST (e.g. smtp-relay.brevo.com), SPRING_MAIL_PORT=587, SPRING_MAIL_USERNAME and SPRING_MAIL_PASSWORD (from Brevo Transactional → SMTP, not the API key), STARTTLS/auth properties, and APP_MAIL_FROM with a sender verified in Brevo. Alternatively add only BREVO_API_KEY (Brevo → API keys, HTTPS) so the contact form works without SMTP. You can still email tiempos.site@gmail.com.",
    errorSmtpSendFailed: "SMTP connected but sending failed or was rejected. In Brevo: verify the sender used in APP_MAIL_FROM, use the SMTP password (xsmtpsib-…), and match SPRING_MAIL_USERNAME to the value shown in Brevo’s SMTP screen. See Render API logs for the exact error. You can still email tiempos.site@gmail.com.",
    faqSectionTitle: "Looking for quick answers?",
    faqSectionText: "Visit our FAQ page for answers to common questions.",
    faqButton: "Visit FAQ",
  ),
  support: StaticTwoField(title: "Support & help", body: "Need help? Check How it works, Cancellation & no-show policy, and the Instructor guide first. If you are stuck, email support@tiempos.local with your account email and a short description.\n\nWe cannot mediate every dispute, but we take abuse and no-show patterns seriously and may restrict accounts to protect the community."),
  terms: LegalDocCopy(title: "Terms of Service", heroSubtitle: "The rules for using Tiempos fairly and safely—profiles, behavior, and time credits.", body: "By creating an account and using Tiempos, you agree to use the service in good faith. You will provide accurate profile information, treat other members with respect, and follow applicable laws.\n\nTime credits are not legal tender, have no cash value, and cannot be redeemed for cash. They exist only to schedule and record skill exchanges inside the platform.\n\nWe may change or discontinue features, send notices in the app, and suspend or restrict accounts that abuse the platform, harass others, or repeatedly break these expectations.\n\nIf we update these terms, we will give reasonable notice where practical. Continued use after changes means you accept the updated terms.\n\nThis page is a plain-language summary for the project. Before a public launch, a complete Terms of Service should be drafted and reviewed with qualified legal counsel."),
  privacy: LegalDocCopy(title: "Privacy Policy", heroSubtitle: "How we use account and profile data, what others can see, and how we protect your information.", body: "Tiempos processes personal data that you provide and that is generated when you use the product—for example: account and login details, profile fields you choose to add, messages and notifications related to bookings, and technical data needed to keep the service secure and reliable.\n\nVisibility: Other signed-in members may see the profile information you choose to publish, according to what each screen and your settings describe (for example public profile fields and skill listings). We do not sell your personal information to third parties as a business model.\n\nCookies and security: We use cookies or similar technologies where needed for authentication, preferences, and security (such as keeping you signed in safely). Use a strong, unique password and do not share your login with others.\n\nRetention and deletion: You may request deletion of your account. Some information may be retained where the law, fraud prevention, or serious safety investigations require it.\n\nThis summary supports trust and transparency during development. A full, jurisdiction-specific privacy policy and data-processing agreements should be finalized before production."),
  policyCancellation: LegalDocCopy(title: "Cancellations & no-show", heroSubtitle: "When you can cancel a session, what “late cancel” and no-show mean, and how time credits move.", body: "Time credits on Tiempos are settled when the instructor marks a session as completed in the product flow. Until then, making or holding a booking does not permanently debit your balance in the same way as a final charge—see in-app help for the exact behavior in your build.\n\nUse this policy as a shared expectation between members:\n\n— More than 2 hours before the scheduled start: cancellation is typically free of credit movement (in most cases nothing has been finally debited yet; confirm in the app).\n\n— Between 1 and 2 hours before the start: treat this as a late cancellation. Tell the other person as soon as possible. Repeated patterns can affect trust signals and community standing.\n\n— Less than 1 hour before the start, or if someone does not show up (no-show): the session may be forfeited; the host may document the situation through Support. Repeated no-shows may lead to account review.\n\nOptional attendance acknowledgment in a thread can help both sides, but it does not replace the instructor’s “complete session” step for moving credits.\n\nThis is a community guideline, not a substitute for legal advice. Adjust time windows in your deployment if needed."),
  instructorGuide: StaticTwoField(title: "Instructor: approval & session flow", body: "1) A learner sends a request with a proposed time. You can Accept, Decline, or Decline and propose a new time (after a decline).\n\n2) After you Accept, the thread opens fully. Add the meeting link (Zoom, Meet, etc.) in the session card so the learner can join. Conflicting accepted sessions are blocked to protect your calendar.\n\n3) When the real session is done, use “Mark session complete” so time credits are transferred. If something goes wrong, cancel before the scheduled start (rules above).\n\n4) Optional: the learner can mark attendance; it does not replace your completion action but helps trust."),
);
